id: P010653
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:18:21.744386
source_metadata:
  id: bdr:W1KG5182
  title: འདུལ་བའི་གླེང་འབུམ།
  author: ''
  volumes:
    41b6e58d42ca4fe08868441259c66c84:
      image_group_id: I1KG5202
      title: ''
      volume_number: 1
      total_pages: 855
      base_file: v001.txt
    4b0355db78874c02b7023018c600e4e1:
      image_group_id: I1KG5203
      title: ''
      volume_number: 2
      total_pages: 910
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
