id: I7916D229
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T01:16:10+00:00'
last_modified: '2022-06-08T16:32:09.707111+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5182
  title: འདུལ་བའི་གླེང་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    FA74:
      image_group_id: I1KG5202
      title: ''
      total_pages: 855
      order: 1
      base_file: FA74.txt
    BB7B:
      image_group_id: I1KG5203
      title: ''
      total_pages: 910
      order: 2
      base_file: BB7B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
