id: I7916D229
legacy_id: P010653
ocr_import_info:
  bdrc_scan_id: W1KG5182
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T01:09:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:12:43.225016+00:00'
last_modified: 2022-09-01 01:13:33.141192
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5182
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5182
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་བའི་གླེང་འབུམ།
  author: དགེ་འདུན་གྲུབ་པ།
statistics:
  ocr_word_mean_confidence_index: 0.5840999020579684
  ocr_word_median_confidence_index: 0.5799999833106995
quality: null
bases:
  I1KG5203:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5203
      total_pages: 910
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG5203.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.6078439627931468
    legacy_id: v002
  I1KG5202:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5202
      total_pages: 855
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5202.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5550229272930992
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
